---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra
  namespace: cluster-config
spec:
  interval: 1m0s
  path: ./infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-config
